name: Deploy dev to Vercel
on:
  pull_request:
    types: closed
    branches:
      - dev

jobs:
  # Deploy to Vercel
  deploy:
    if: github.event.pull_request.merged == true
    name: Vercel Deploy Pipeline
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        node-version: ["16.x"]
    steps:
      - uses: actions/checkout@v2

      # Initialize Nodejs
      - name: Install Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Deploy to Vercel
        run: npx vercel --token ${VERCEL_TOKEN} --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_DEV_PROJECT_ID}}
